#cloud-config
repo_update: true
write_files:
  - path: /run-container.sh
    permissions: 755
    content: |
      #!/bin/bash
      echo "${USERDATA_BEGIN}" >> /var/log/userdata-output

      if podman pull ${VALIDATOR_IMAGE}; then
        echo "Using IMAGE: $(podman images ${VALIDATOR_IMAGE} -q)" >> /var/log/userdata-output
      
        if [[ "${CACERT}" != "" ]]; then
          echo "${CACERT}" | base64 --decode > /proxy.pem
          podman run \
            -v /proxy.pem:/proxy.pem \
            --env "HTTP_PROXY=${HTTP_PROXY}" \
            --env "HTTPS_PROXY=${HTTPS_PROXY}" \
            --env "AWS_REGION=${AWS_REGION}" \
            --env "START_VERIFIER=${VALIDATOR_START_VERIFIER}" \
            --env "END_VERIFIER=${VALIDATOR_END_VERIFIER}" \
            "$(podman images ${VALIDATOR_IMAGE} -q)" \
            --cacert=/proxy.pem \
            --no-tls=${NOTLS}  >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
        else
          podman run \
            --env "AWS_REGION=${AWS_REGION}" \
            --env "HTTP_PROXY=${HTTP_PROXY}" \
            --env "START_VERIFIER=${VALIDATOR_START_VERIFIER}" \
            --env "END_VERIFIER=${VALIDATOR_END_VERIFIER}" \
            "$(podman images ${VALIDATOR_IMAGE} -q)" >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
        fi

      else
        echo "Warning: could not pull the specified docker image, will try to use the prepulled one" >> /var/log/userdata-output
        echo "Using IMAGE: $(podman images quay.io/app-sre/osd-network-verifier -q | head -n 1)" >> /var/log/userdata-output
      
        if [[ "${CACERT}" != "" ]]; then
          echo "${CACERT}" | base64 --decode > /proxy.pem
          podman run \
            -v /proxy.pem:/proxy.pem \
            --env "HTTP_PROXY=${HTTP_PROXY}" \
            --env "HTTPS_PROXY=${HTTPS_PROXY}" \
            --env "AWS_REGION=${AWS_REGION}" \
            --env "START_VERIFIER=${VALIDATOR_START_VERIFIER}" \
            --env "END_VERIFIER=${VALIDATOR_END_VERIFIER}" \
            "$(podman images quay.io/app-sre/osd-network-verifier} -q | head -n 1)" \
            --cacert=/proxy.pem \
            --no-tls=${NOTLS}  >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
        else
          podman run \
            --env "AWS_REGION=${AWS_REGION}" \
            --env "HTTP_PROXY=${HTTP_PROXY}" \
            --env "START_VERIFIER=${VALIDATOR_START_VERIFIER}" \
            --env "END_VERIFIER=${VALIDATOR_END_VERIFIER}" \
            "$(podman images quay.io/app-sre/osd-network-verifier -q | head -n 1)" >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
        fi
      fi

      echo "${USERDATA_END}" >> /var/log/userdata-output
runcmd:
  - /run-container.sh
  - cat /var/log/userdata-output >/dev/console
